# Generated by Django 4.0.5 on 2022-07-01 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('element_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='element_id')),
                ('element_name', models.CharField(max_length=1000, verbose_name='element_name')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
            ],
            options={
                'db_table': 'content_model_reference',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(default='null', max_length=255, verbose_name='title')),
                ('company_name', models.CharField(default='null', max_length=255, verbose_name='company_name')),
                ('job_link', models.CharField(default='null', max_length=1000, verbose_name='job_link')),
                ('company_link', models.CharField(default='null', max_length=1000, verbose_name='company_link')),
                ('location', models.CharField(default='null', max_length=500, verbose_name='location')),
                ('time_posted', models.CharField(default='null', max_length=50, verbose_name='time_posted')),
                ('time_extracted', models.CharField(default='null', max_length=50, verbose_name='time_extracted')),
                ('num_of_applicants', models.CharField(default='null', max_length=255, verbose_name='no_of_applicants')),
                ('description', models.TextField(default='null', verbose_name='description')),
                ('salary', models.CharField(default='null', max_length=1000, verbose_name='salary')),
                ('rating_link', models.CharField(default='null', max_length=100, verbose_name='rating_link')),
                ('rating_avg', models.CharField(default='null', max_length=10, verbose_name='rating_avg')),
                ('rating_count', models.CharField(default='null', max_length=10, verbose_name='rating_count')),
                ('medium', models.CharField(choices=[('indeed', 'Indeed'), ('cvlib', 'CvLibrary'), ('adzuna', 'Adzuna'), ('reeds', 'Reeds'), ('guardian', 'Guardian'), ('jobstoday', 'JobsToday'), ('wework', 'WeWork'), ('jobsac', 'JobsAc'), ('charity', 'CharityJob'), ('findajob', 'Find a job'), ('tes', 'TES')], default='null', max_length=20, verbose_name='medium')),
                ('remote', models.BooleanField(verbose_name='remote')),
                ('job_type', models.CharField(default='null', max_length=50, verbose_name='job_type')),
            ],
        ),
        migrations.CreateModel(
            name='JobTitles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('onetsoc_code', models.CharField(max_length=25, verbose_name='onet_id')),
                ('title', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'db_table': 'occupation_data',
            },
        ),
        migrations.CreateModel(
            name='TechSkills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='OtherSkills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobtitles')),
                ('other_skill_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobtitles')),
                ('knowledge_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contentmodel')),
            ],
        ),
        migrations.AddField(
            model_name='jobtitles',
            name='tech_skills',
            field=models.ManyToManyField(to='api.techskills'),
        ),
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('element_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contentmodel')),
                ('onetsoc_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobtitles')),
            ],
            options={
                'db_table': 'abilities',
            },
        ),
    ]
