# Generated by Django 4.0.5 on 2022-07-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilities',
            name='not_relevant',
            field=models.CharField(max_length=5, null=True, verbose_name='not_relevant'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='not_relevant',
            field=models.CharField(max_length=5, null=True, verbose_name='not_relevant'),
        ),
        migrations.AddField(
            model_name='otherskills',
            name='not_relevant',
            field=models.CharField(max_length=5, null=True, verbose_name='not_relevant'),
        ),
    ]
