# Generated by Django 4.0.5 on 2022-07-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_abilities_not_relevant_knowledge_not_relevant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtitles',
            name='tech_skills',
        ),
        migrations.AddField(
            model_name='jobs',
            name='avg_sal',
            field=models.FloatField(null=True, verbose_name='avg_sal'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='county',
            field=models.CharField(max_length=100, null=True, verbose_name='county'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='date_posted',
            field=models.CharField(max_length=50, null=True, verbose_name='date_posted'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='higher_sal',
            field=models.FloatField(null=True, verbose_name='higher_sal'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_type1',
            field=models.CharField(max_length=100, null=True, verbose_name='job_type1'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_type2',
            field=models.CharField(max_length=100, null=True, verbose_name='job_type2'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='lower_sal',
            field=models.FloatField(null=True, verbose_name='lower_sal'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='sal_freq',
            field=models.CharField(max_length=20, null=True, verbose_name='sal_freq'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='state',
            field=models.CharField(max_length=100, null=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='not_relevant',
            field=models.CharField(max_length=10, null=True, verbose_name='relevant'),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='onetsoc_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobtitles', to_field='onetsoc_code'),
        ),
        migrations.AlterField(
            model_name='jobtitles',
            name='onetsoc_code',
            field=models.CharField(db_index=True, max_length=25, unique=True, verbose_name='onet_id'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobtitles', to_field='onetsoc_code'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='not_relevant',
            field=models.CharField(max_length=10, null=True, verbose_name='relevant'),
        ),
        migrations.AlterField(
            model_name='otherskills',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobtitles', to_field='onetsoc_code'),
        ),
        migrations.AlterField(
            model_name='otherskills',
            name='not_relevant',
            field=models.CharField(max_length=10, null=True, verbose_name='relevant'),
        ),
        migrations.CreateModel(
            name='TechSkillTitle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('hot_tech', models.CharField(max_length=5, verbose_name='hot_tech')),
                ('jobtitles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobtitles', to_field='onetsoc_code')),
                ('techskills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.techskills', to_field='name')),
            ],
            options={
                'db_table': 'occupation_data_tech_skills',
            },
        ),
    ]
