# Generated by Django 4.0.5 on 2022-07-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_jobtitles_tech_skills_jobs_avg_sal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='city'),
        ),
    ]
